title: Lucas E. Suryana # your name (or website title) here
logo: "/images/lucas-logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bandung Institute of Technology
  Engineering Physics (2016) - B.Sc.
  Instrumentation & Control (2019) - M.Sc.
  <br><br>
  <a href="https://www.linkedin.com/in/lucas-elbert-suryana-b84805b9/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
